obj-m+=sys_read_task_struct.o

all:
	gcc Q1_A1.c -o Q1_A1 -lpthread
	gcc Q1_A2.c -o Q1_A2 -lpthread
	gcc Q1_B1.c -o Q1_B1 -lpthread
	gcc Q1_B2.c -o Q1_B2 -lpthread
	
clean:
	rm Q1_A1 Q1_B1 Q1_A2 Q1_B2
