all: 
	gcc Dining_Philosopher_Semaphores.c -o Dining_Philosopher_Semaphores
	gcc Modified_Dining_Philosopher.c -o Modified_Dining_Philosopher
	gcc Dining_Philosopher_2.c -o Dining_Philosopher_2
	gcc Modified_Dining_Philosopher_2.c -o Modified_Dining_Philosopher_2
	
clean: 
	rm Dining_Philosopher_Semaphores Dining_Philosopher_2 Modified_Dining_Philosopher Modified_Dining_Philosopher_2
	
