all: 
	gcc Dining_Philosopher_Semaphores.c -o Dining_Philosopher_Semaphores -lpthread
	gcc Modified_Dining_Philosopher.c -o Modified_Dining_Philosopher -lpthread
	gcc Dining_Philosopher_2.c -o Dining_Philosopher_2 -lpthread
	gcc Modified_Dining_Philosopher_2.c -o Modified_Dining_Philosopher_2 -lpthread
	
clean: 
	rm Dining_Philosopher_Semaphores Dining_Philosopher_2 Modified_Dining_Philosopher Modified_Dining_Philosopher_2
	
