compile:
	gcc P1_FIFO.c -o P1_FIFO
	gcc P2_FIFO.c -o P2_FIFO
	gcc P1_Socket.c -o P1_Socket
	gcc P2_Socket.c -o P2_Socket
	gcc P1_Shared_Memory.c -o P1_Shared_Memory
	gcc P2_Shared_Memory.c -o P2_Shared_Memory


clean: 
	rm  P1_FIFO P2_FIFO P1_Socket P2_Socket P1_Shared_Memory P2_Shared_Memory SOCKET_1.socket
